import fs from 'fs';
import path from 'path';

export interface GenerateImageInput {
  title: string;
  category?: string;
  brandName?: string;
  primaryColor?: string;
  secondaryColor?: string;
}

export interface GenerateImageResult {
  success: boolean;
  imageUrl: string;
  provider: string;
}

export class TemplateImageProvider {
  name = 'template';

  async generateImage(input: GenerateImageInput): Promise<GenerateImageResult> {
    const outputDir = path.join(process.cwd(), 'public', 'renders');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const filename = `image-${Date.now()}.svg`;
    const outputPath = path.join(outputDir, filename);
    const publicUrl = `/renders/${filename}`;

    const pColor = input.primaryColor || '#6366F1';
    const sColor = input.secondaryColor || '#10B981';
    const brand = input.brandName || 'SMRITS CONTENT AI';
    const title = input.title || 'Tech Trend Breakdown';
    const category = input.category || 'AI TOOL';

    const svgContent = `
<svg width="1080" height="1920" viewBox="0 0 1080 1920" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="1080" height="1920" fill="#0F172A"/>
  
  <!-- Dynamic Gradient Background Overlay -->
  <circle cx="540" cy="400" r="500" fill="${pColor}" opacity="0.25" filter="blur(80px)"/>
  <circle cx="540" cy="1400" r="600" fill="${sColor}" opacity="0.20" filter="blur(90px)"/>
  
  <!-- Card Container -->
  <rect x="80" y="240" width="920" height="1440" rx="40" fill="#1E293B" stroke="#334155" stroke-width="4"/>
  
  <!-- Category Badge -->
  <rect x="140" y="320" width="240" height="60" rx="30" fill="${pColor}"/>
  <text x="260" y="360" fill="#FFFFFF" font-family="sans-serif" font-size="24" font-weight="bold" text-anchor="middle">${category}</text>
  
  <!-- Title Text -->
  <foreignObject x="140" y="440" width="800" height="400">
    <div xmlns="http://www.w3.org/1999/xhtml" style="color: white; font-family: sans-serif; font-size: 64px; font-weight: 800; line-height: 1.2;">
      ${title}
    </div>
  </foreignObject>
  
  <!-- Decorative Code Icon Graphic -->
  <rect x="140" y="900" width="800" height="500" rx="24" fill="#090D16" stroke="#334155"/>
  <text x="180" y="980" fill="#10B981" font-family="monospace" font-size="32">// Generated by SMRITS AI Studio</text>
  <text x="180" y="1040" fill="#60A5FA" font-family="monospace" font-size="28">const content = await smrits.generate({</text>
  <text x="220" y="1100" fill="#F59E0B" font-family="monospace" font-size="28">topic: "${title.slice(0, 25)}...",</text>
  <text x="220" y="1160" fill="#EC4899" font-family="monospace" font-size="28">viralScore: 98,</text>
  <text x="180" y="1220" fill="#60A5FA" font-family="monospace" font-size="28">});</text>

  <!-- Footer Watermark & Brand -->
  <text x="540" y="1780" fill="#94A3B8" font-family="sans-serif" font-size="32" font-weight="600" text-anchor="middle">⚡ ${brand}</text>
</svg>
    `.trim();

    fs.writeFileSync(outputPath, svgContent, 'utf-8');

    return {
      success: true,
      imageUrl: publicUrl,
      provider: 'LOCAL SVG TEMPLATE ENGINE',
    };
  }
}
